import traceback

def printError():
    traceback.print_exc()